### ISSUE TITLE
Network name off by one

### ISSUE THREAD

**Issue by skysingh** [ropg/M5ez#32] opened 2019-02-28 16:57 UTC
When you ask it to forget a network name it removes the next one down,. So to forget the first network you have to remove every other one. Somehow the pointer is off by one.

**Comment by ropg** [comment] 2019-06-07 18:45
Hi there, sorry for late reply. I cannot reproduce this. When you say "When you ask it ...", do you mean through the wifi menu, or from code with `ez.wifi.remove` ?

**Comment by ropg** [comment] 2019-06-07 19:05
Fixed in 2.1.0

**Closed by ropg** 2019-06-07 19:05 UTC
